# src/CKM/AppBundle/Resources/config/routing.yml
CKMAppBundle_homepage:
    pattern:  /
    defaults: { _controller: CKMAppBundle:Page:index }
## pages communication
CKMAppBundle_communication:
    pattern:  /communication
    defaults: { _controller: CKMAppBundle:Page:communication }
## pages documentation
CKMAppBundle_documentation_datacard_input:
    pattern:  /documentation/datacard/{scenario}/{input}
    defaults: { _controller: CKMAppBundle:Documentation:seeDatacardInputDocumentation}
## pages analyse
CKMAppBundle_analyse_definition:
    pattern:  /analysis/definition
    defaults: { _controller: CKMAppBundle:Analysis:definition }
CKMAppBundle_analyse_testform:
    pattern:  /analysis/testform
    defaults: { _controller: CKMAppBundle:Analysis:testform }
CKMAppBundle_analyse_source:
    pattern:  /analysis/source/
    defaults: { _controller: CKMAppBundle:Analysis:source }
CKMAppBundle_analyse_create_analyse:
    pattern:  /analysis/createAnalyse/
    defaults: { _controller: CKMAppBundle:Analysis:createAnalyse }
CKMAppBundle_analyse_create_analyse_source:
    pattern:  /analysis/createAnalyseSource/{analyse}/{step}
    defaults: { _controller: CKMAppBundle:Analysis:createAnalyseSource, analyse:null, step:0}
    requirements:
        analyse:  \d+
        step:  \d+
CKMAppBundle_analyse_create_analyse_source_input:
    pattern:  /analysis/createAnalyseSourceInput/{type}/{input_id}
    defaults: { _controller: CKMAppBundle:Analysis:editInput}
CKMAppBundle_analyse_create_analyse_source_input_tag:
    pattern:  /analysis/createAnalyseSourceInputTag/{input_id}
    defaults: { _controller: CKMAppBundle:Analysis:editInputTag}
CKMAppBundle_analyse_create_analyse_source_parameter:
    pattern:  /analysis/createAnalyseSourceParameter/{parameter_id}
    defaults: { _controller: CKMAppBundle:Analysis:editParameter}
CKMAppBundle_analyse_create_analyse_properties:
    pattern:  /analysis/createAnalyseProperties/{analyse}
    defaults: { _controller: CKMAppBundle:Analysis:editAnalysisProperties}
CKMAppBundle_analyse_create_analyse_scan:
    pattern:  /analysis/createAnalyseScan/{target_id}
    defaults: { _controller: CKMAppBundle:Analysis:editAnalysisScan}
CKMAppBundle_analyse_create_analyse_remove:
    pattern:  /analysis/createAnalyseRemove/{analyse}
    defaults: { _controller: CKMAppBundle:Analysis:removeAnalysis}
CKMAppBundle_analyse_by_user:
    pattern:  /analysis/byuser/{user_id}/{page}
    defaults: { _controller: CKMAppBundle:Analysis:analysisByUser, page: 1}
# analyse 2eme version
CKMAppBundle_analyse_create_step_1:
    pattern:  /analysis/createAnalyse/step1
    defaults: { _controller: CKMAppBundle:Analysis:createAnalyseStep1}
CKMAppBundle_analyse_create_step_2:
    pattern:  /analysis/createAnalyse/step2/{analyse}/{step}
    defaults: { _controller: CKMAppBundle:Analysis:createAnalyseStep2}
    requirements:
        analyse:  \d+
CKMAppBundle_analyse_create_step_3:
    pattern:  /analysis/createAnalyse/step3/{analyse}/{step}
    defaults: { _controller: CKMAppBundle:Analysis:createAnalyseStep3}
    requirements:
        analyse:  \d+
CKMAppBundle_analyse_see_datacard:
    pattern:  /analysis/datacard/see/{analyse}
    defaults: { _controller: CKMAppBundle:Analysis:seeDatacard}
CKMAppBundle_analyse_create_analyse_finalize:
    pattern:  /analysis/run/{analyse}
    defaults: { _controller: CKMAppBundle:Analysis:finalize}
CKMAppBundle_analyse_create_analyse_copy:
    pattern:  /analysis/copy/{analyse}
    defaults: { _controller: CKMAppBundle:Analysis:copy}
## pages administration
CKMAppBundle_administration_datacard_add:
    pattern:  /administration/datacard/add
    defaults: { _controller: CKMAppBundle:Administration:addDatacard}
CKMAppBundle_administration_datacard:
    pattern:  /administration/datacard/
    defaults: { _controller: CKMAppBundle:Administration:datacard}
CKMAppBundle_administration_datacard_documentation:
    pattern:  /administration/datacard/documentation/
    defaults: { _controller: CKMAppBundle:Administration:datacardDocumentation}
CKMAppBundle_administration_datacard_documentation_add:
    pattern:  /administration/datacard/documentation/add/{display}
    defaults: { _controller: CKMAppBundle:Administration:addDatacardDocumentation}
CKMAppBundle_administration_latex_documentation:
    pattern:  /administration/latex/documentation/
    defaults: { _controller: CKMAppBundle:Administration:latexDocumentation}
CKMAppBundle_administration_latex_documentation_add:
    pattern:  /administration/latex/documentation/add
    defaults: { _controller: CKMAppBundle:Administration:addLatex}
CKMAppBundle_administration_latex_documentation_edit:
    pattern:  /administration/latex/documentation/edit/{latex}
    defaults: { _controller: CKMAppBundle:Administration:editLatex}
CKMAppBundle_administration_latex_documentation_delete:
    pattern:  /administration/latex/documentation/delete/{latex}
    defaults: { _controller: CKMAppBundle:Administration:deleteLatex}
## test
CKMAppBundle_test_datacard:
    pattern:  /administration/datacard/test/{analyse}
    defaults: { _controller: CKMAppBundle:Analysis:testDatacard}
