parameters:
#    ckm_app.example.class: CKM\AppBundle\Example

services:
#    ckm_app.example:
#        class: %ckm_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my.twig.extension:
        class: CKM\AppBundle\Twig\CKMExtension
        tags:
            -  { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"
