<?php

namespace CKM\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnalysisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysisRepository extends EntityRepository
{
    public function countTargetByAnalyse($id)
    {
      $em = $this->getEntityManager();
      $query = $em->createQuery('SELECT COUNT(e.id) FROM CKM\AppBundle\Entity\ElementTarget e WHERE e.analyse_id = :analyse');
      $query->setParameter('analyse', $id );
      $count = $query->getSingleScalarResult();
      return $count;
    }
}
