<?php

namespace CKM\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObservableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservableRepository extends EntityRepository
{
    /**
     * select all observable input (target and input)
     */
    public function findByObservableAnalysis($analyse)
    {
      $input=true;
      return $this->getEntityManager()
          ->createQuery(
              'SELECT o FROM CKM\AppBundle\Entity\Observable o WHERE o.analyse = :analyse and o.isInput=:input'
          )
          ->setParameters(array(
                'analyse'   => $analyse,
                'input'    => $input,
                )
           )
          ->getResult();
    }

    /**
     * select all input (observables that are just input and are not target)
     */
    public function findByInputAnalysis($analyse)
    {
      $input  = true;
      $target = false;
      return $this->getEntityManager()
          ->createQuery(
              'SELECT o FROM CKM\AppBundle\Entity\Observable o WHERE o.analyse = :analyse and o.isInput=:input and o.isTarget=:target'
          )
          ->setParameters(array(
                'analyse'   => $analyse,
                'input'     => $input,
                'target'    => $target,
                )
           )
          ->getResult();
    }

    /**
     * select observables that are both input and target)
     */
    public function findByInputTargetAnalysis($analyse)
    {
      $input  = true;
      $target = true;
      return $this->getEntityManager()
          ->createQuery(
              'SELECT o FROM CKM\AppBundle\Entity\Observable o WHERE o.analyse = :analyse and o.isInput=:input and o.isTarget=:target'
          )
          ->setParameters(array(
                'analyse'   => $analyse,
                'input'     => $input,
                'target'    => $target,
                )
           )
          ->getResult();
    }

    /**
     * select all Observable
     */
    public function findByAnalysis($analyse)
    {
      return $this->getEntityManager()
          ->createQuery(
              'SELECT o FROM CKM\AppBundle\Entity\Observable o WHERE o.analyse = :analyse'
          )
          ->setParameters(array(
                'analyse'   => $analyse,
                )
           )
          ->getResult();
    }
}