<?php

namespace CKM\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlottingRepository extends EntityRepository
{
  public function countNumberOfPlot($analysis)
  {
    $em = $this->getEntityManager();
    $query = $em->createQuery('SELECT COUNT(p.id) FROM CKM\AppBundle\Entity\Plotting p WHERE p.analysis = :analyse');
    $query->setParameter('analyse', $analysis );
    $count = $query->getSingleScalarResult();

    $count++;
    echo $analysis." - ".$count." - ";

    return $count;
  }

  public function findLastPlottingByAnalysis($analysis)
  {
    $em = $this->getEntityManager();
    $query = $em->createQuery('SELECT p FROM CKM\AppBundle\Entity\Plotting p WHERE p.analysis = :analyse ORDER BY p.numberOfPlot')
    ->setParameter('analyse', $analysis )
    ->setMaxResults(5)
    ->setFirstResult(1);
    return $query->getOneOrNullResult();
  }
}
